"""tabelas_finais

Revision ID: 387e50d3f172
Revises: 
Create Date: 2026-09-30 10:47:43.456285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387e50d3f172'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_id'), 'curso', ['id'], unique=False)
    op.create_table('disciplina',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_index(op.f('ix_disciplina_codigo'), 'disciplina', ['codigo'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.Enum('ADMIN', 'USUARIO', name='papelusuario'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('aluno',
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('cidade_nasceu', sa.String(length=100), nullable=True),
    sa.Column('municipio_reside', sa.String(length=100), nullable=True),
    sa.Column('ira', sa.Float(), nullable=True),
    sa.Column('formado', sa.Boolean(), nullable=True),
    sa.Column('semestre_atual', sa.Integer(), nullable=True),
    sa.Column('ano_ingresso', sa.String(length=100), nullable=True),
    sa.Column('prazo_conclusao', sa.String(length=100), nullable=True),
    sa.Column('ch_total', sa.Float(), nullable=True),
    sa.Column('qtd_trancamentos', sa.Integer(), nullable=True),
    sa.Column('total_reprovacoes', sa.Integer(), nullable=True),
    sa.Column('media_notas', sa.Float(), nullable=True),
    sa.Column('variancia_notas', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.create_index(op.f('ix_aluno_matricula'), 'aluno', ['matricula'], unique=False)
    op.create_table('historico_disciplina',
    sa.Column('aluno_matricula', sa.Integer(), nullable=False),
    sa.Column('disciplina_codigo', sa.String(length=200), nullable=False),
    sa.Column('status_conclusao', sa.Boolean(), nullable=True),
    sa.Column('qtd_reprovado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_matricula'], ['aluno.matricula'], ),
    sa.ForeignKeyConstraint(['disciplina_codigo'], ['disciplina.codigo'], ),
    sa.PrimaryKeyConstraint('aluno_matricula', 'disciplina_codigo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_disciplina')
    op.drop_index(op.f('ix_aluno_matricula'), table_name='aluno')
    op.drop_table('aluno')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_disciplina_codigo'), table_name='disciplina')
    op.drop_table('disciplina')
    op.drop_index(op.f('ix_curso_id'), table_name='curso')
    op.drop_table('curso')
    # ### end Alembic commands ###
